// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LinksColumns holds the columns for the "links" table.
	LinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "domain", Type: field.TypeString, Nullable: true},
		{Name: "og_image", Type: field.TypeString, Nullable: true},
		{Name: "page_url", Type: field.TypeString, Nullable: true},
		{Name: "note", Type: field.TypeString, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "saved_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// LinksTable holds the schema information for the "links" table.
	LinksTable = &schema.Table{
		Name:       "links",
		Columns:    LinksColumns,
		PrimaryKey: []*schema.Column{LinksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "link_user_id_saved_at",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[1], LinksColumns[11]},
			},
			{
				Name:    "link_domain",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[5]},
			},
			{
				Name:    "link_published_at",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[13]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LinksTable,
	}
)

func init() {
}
