// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LinksColumns holds the columns for the "links" table.
	LinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Default: schema.Expr("gen_random_uuid()")},
		{Name: "user_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "url", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "title", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "domain", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "og_image", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "page_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "note", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Default: schema.Expr("'{}'::jsonb")},
		{Name: "saved_at", Type: field.TypeTime, Default: schema.Expr("now()")},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("now()")},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// LinksTable holds the schema information for the "links" table.
	LinksTable = &schema.Table{
		Name:       "links",
		Columns:    LinksColumns,
		PrimaryKey: []*schema.Column{LinksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_links_user_saved_at",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[1], LinksColumns[11]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						LinksColumns[11].Name: true,
					},
				},
			},
			{
				Name:    "idx_links_domain",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[5]},
			},
			{
				Name:    "idx_links_published_at",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[13]},
			},
			{
				Name:    "idx_links_tags_gin",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[9]},
				Annotation: &entsql.IndexAnnotation{
					Type: "GIN",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LinksTable,
	}
)

func init() {
}
