// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvncer/quicklinks/api/ent/link"
)

// LinkCreate is the builder for creating a Link entity.
type LinkCreate struct {
	config
	mutation *LinkMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *LinkCreate) SetUserID(v string) *LinkCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *LinkCreate) SetNillableUserID(v *string) *LinkCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *LinkCreate) SetURL(v string) *LinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *LinkCreate) SetTitle(v string) *LinkCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *LinkCreate) SetNillableTitle(v *string) *LinkCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *LinkCreate) SetDescription(v string) *LinkCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LinkCreate) SetNillableDescription(v *string) *LinkCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *LinkCreate) SetDomain(v string) *LinkCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *LinkCreate) SetNillableDomain(v *string) *LinkCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetOgImage sets the "og_image" field.
func (_c *LinkCreate) SetOgImage(v string) *LinkCreate {
	_c.mutation.SetOgImage(v)
	return _c
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (_c *LinkCreate) SetNillableOgImage(v *string) *LinkCreate {
	if v != nil {
		_c.SetOgImage(*v)
	}
	return _c
}

// SetPageURL sets the "page_url" field.
func (_c *LinkCreate) SetPageURL(v string) *LinkCreate {
	_c.mutation.SetPageURL(v)
	return _c
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_c *LinkCreate) SetNillablePageURL(v *string) *LinkCreate {
	if v != nil {
		_c.SetPageURL(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *LinkCreate) SetNote(v string) *LinkCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *LinkCreate) SetNillableNote(v *string) *LinkCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *LinkCreate) SetTags(v []string) *LinkCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *LinkCreate) SetMetadata(v map[string]interface{}) *LinkCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetSavedAt sets the "saved_at" field.
func (_c *LinkCreate) SetSavedAt(v time.Time) *LinkCreate {
	_c.mutation.SetSavedAt(v)
	return _c
}

// SetNillableSavedAt sets the "saved_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableSavedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetSavedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCreate) SetCreatedAt(v time.Time) *LinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableCreatedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *LinkCreate) SetPublishedAt(v time.Time) *LinkCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillablePublishedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkCreate) SetID(v uuid.UUID) *LinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LinkCreate) SetNillableID(v *uuid.UUID) *LinkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LinkMutation object of the builder.
func (_c *LinkCreate) Mutation() *LinkMutation {
	return _c.mutation
}

// Save creates the Link in the database.
func (_c *LinkCreate) Save(ctx context.Context) (*Link, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCreate) SaveX(ctx context.Context) *Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCreate) defaults() {
	if _, ok := _c.mutation.Metadata(); !ok {
		v := link.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.SavedAt(); !ok {
		v := link.DefaultSavedAt()
		_c.mutation.SetSavedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := link.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := link.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Link.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	return nil
}

func (_c *LinkCreate) sqlSave(ctx context.Context) (*Link, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCreate) createSpec() (*Link, *sqlgraph.CreateSpec) {
	var (
		_node = &Link{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(link.Table, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(link.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(link.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
		_node.Domain = &value
	}
	if value, ok := _c.mutation.OgImage(); ok {
		_spec.SetField(link.FieldOgImage, field.TypeString, value)
		_node.OgImage = &value
	}
	if value, ok := _c.mutation.PageURL(); ok {
		_spec.SetField(link.FieldPageURL, field.TypeString, value)
		_node.PageURL = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(link.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(link.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(link.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.SavedAt(); ok {
		_spec.SetField(link.FieldSavedAt, field.TypeTime, value)
		_node.SavedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(link.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	return _node, _spec
}

// LinkCreateBulk is the builder for creating many Link entities in bulk.
type LinkCreateBulk struct {
	config
	err      error
	builders []*LinkCreate
}

// Save creates the Link entities in the database.
func (_c *LinkCreateBulk) Save(ctx context.Context) ([]*Link, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Link, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCreateBulk) SaveX(ctx context.Context) []*Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
