// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvncer/quicklinks/api/ent/link"
)

// LinkCreate is the builder for creating a Link entity.
type LinkCreate struct {
	config
	mutation *LinkMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (lc *LinkCreate) SetUserID(s string) *LinkCreate {
	lc.mutation.SetUserID(s)
	return lc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (lc *LinkCreate) SetNillableUserID(s *string) *LinkCreate {
	if s != nil {
		lc.SetUserID(*s)
	}
	return lc
}

// SetURL sets the "url" field.
func (lc *LinkCreate) SetURL(s string) *LinkCreate {
	lc.mutation.SetURL(s)
	return lc
}

// SetTitle sets the "title" field.
func (lc *LinkCreate) SetTitle(s string) *LinkCreate {
	lc.mutation.SetTitle(s)
	return lc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (lc *LinkCreate) SetNillableTitle(s *string) *LinkCreate {
	if s != nil {
		lc.SetTitle(*s)
	}
	return lc
}

// SetDescription sets the "description" field.
func (lc *LinkCreate) SetDescription(s string) *LinkCreate {
	lc.mutation.SetDescription(s)
	return lc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (lc *LinkCreate) SetNillableDescription(s *string) *LinkCreate {
	if s != nil {
		lc.SetDescription(*s)
	}
	return lc
}

// SetDomain sets the "domain" field.
func (lc *LinkCreate) SetDomain(s string) *LinkCreate {
	lc.mutation.SetDomain(s)
	return lc
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (lc *LinkCreate) SetNillableDomain(s *string) *LinkCreate {
	if s != nil {
		lc.SetDomain(*s)
	}
	return lc
}

// SetOgImage sets the "og_image" field.
func (lc *LinkCreate) SetOgImage(s string) *LinkCreate {
	lc.mutation.SetOgImage(s)
	return lc
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (lc *LinkCreate) SetNillableOgImage(s *string) *LinkCreate {
	if s != nil {
		lc.SetOgImage(*s)
	}
	return lc
}

// SetPageURL sets the "page_url" field.
func (lc *LinkCreate) SetPageURL(s string) *LinkCreate {
	lc.mutation.SetPageURL(s)
	return lc
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (lc *LinkCreate) SetNillablePageURL(s *string) *LinkCreate {
	if s != nil {
		lc.SetPageURL(*s)
	}
	return lc
}

// SetNote sets the "note" field.
func (lc *LinkCreate) SetNote(s string) *LinkCreate {
	lc.mutation.SetNote(s)
	return lc
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (lc *LinkCreate) SetNillableNote(s *string) *LinkCreate {
	if s != nil {
		lc.SetNote(*s)
	}
	return lc
}

// SetTags sets the "tags" field.
func (lc *LinkCreate) SetTags(s []string) *LinkCreate {
	lc.mutation.SetTags(s)
	return lc
}

// SetMetadata sets the "metadata" field.
func (lc *LinkCreate) SetMetadata(m map[string]interface{}) *LinkCreate {
	lc.mutation.SetMetadata(m)
	return lc
}

// SetSavedAt sets the "saved_at" field.
func (lc *LinkCreate) SetSavedAt(t time.Time) *LinkCreate {
	lc.mutation.SetSavedAt(t)
	return lc
}

// SetNillableSavedAt sets the "saved_at" field if the given value is not nil.
func (lc *LinkCreate) SetNillableSavedAt(t *time.Time) *LinkCreate {
	if t != nil {
		lc.SetSavedAt(*t)
	}
	return lc
}

// SetCreatedAt sets the "created_at" field.
func (lc *LinkCreate) SetCreatedAt(t time.Time) *LinkCreate {
	lc.mutation.SetCreatedAt(t)
	return lc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lc *LinkCreate) SetNillableCreatedAt(t *time.Time) *LinkCreate {
	if t != nil {
		lc.SetCreatedAt(*t)
	}
	return lc
}

// SetPublishedAt sets the "published_at" field.
func (lc *LinkCreate) SetPublishedAt(t time.Time) *LinkCreate {
	lc.mutation.SetPublishedAt(t)
	return lc
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (lc *LinkCreate) SetNillablePublishedAt(t *time.Time) *LinkCreate {
	if t != nil {
		lc.SetPublishedAt(*t)
	}
	return lc
}

// SetID sets the "id" field.
func (lc *LinkCreate) SetID(u uuid.UUID) *LinkCreate {
	lc.mutation.SetID(u)
	return lc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lc *LinkCreate) SetNillableID(u *uuid.UUID) *LinkCreate {
	if u != nil {
		lc.SetID(*u)
	}
	return lc
}

// Mutation returns the LinkMutation object of the builder.
func (lc *LinkCreate) Mutation() *LinkMutation {
	return lc.mutation
}

// Save creates the Link in the database.
func (lc *LinkCreate) Save(ctx context.Context) (*Link, error) {
	lc.defaults()
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LinkCreate) SaveX(ctx context.Context) *Link {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LinkCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LinkCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *LinkCreate) defaults() {
	if _, ok := lc.mutation.Metadata(); !ok {
		v := link.DefaultMetadata
		lc.mutation.SetMetadata(v)
	}
	if _, ok := lc.mutation.SavedAt(); !ok {
		v := link.DefaultSavedAt()
		lc.mutation.SetSavedAt(v)
	}
	if _, ok := lc.mutation.CreatedAt(); !ok {
		v := link.DefaultCreatedAt()
		lc.mutation.SetCreatedAt(v)
	}
	if _, ok := lc.mutation.ID(); !ok {
		v := link.DefaultID()
		lc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LinkCreate) check() error {
	if _, ok := lc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Link.url"`)}
	}
	if v, ok := lc.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	if _, ok := lc.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Link.metadata"`)}
	}
	if _, ok := lc.mutation.SavedAt(); !ok {
		return &ValidationError{Name: "saved_at", err: errors.New(`ent: missing required field "Link.saved_at"`)}
	}
	if _, ok := lc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Link.created_at"`)}
	}
	return nil
}

func (lc *LinkCreate) sqlSave(ctx context.Context) (*Link, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LinkCreate) createSpec() (*Link, *sqlgraph.CreateSpec) {
	var (
		_node = &Link{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(link.Table, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	)
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := lc.mutation.UserID(); ok {
		_spec.SetField(link.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := lc.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := lc.mutation.Title(); ok {
		_spec.SetField(link.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := lc.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := lc.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
		_node.Domain = &value
	}
	if value, ok := lc.mutation.OgImage(); ok {
		_spec.SetField(link.FieldOgImage, field.TypeString, value)
		_node.OgImage = &value
	}
	if value, ok := lc.mutation.PageURL(); ok {
		_spec.SetField(link.FieldPageURL, field.TypeString, value)
		_node.PageURL = &value
	}
	if value, ok := lc.mutation.Note(); ok {
		_spec.SetField(link.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := lc.mutation.Tags(); ok {
		_spec.SetField(link.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := lc.mutation.Metadata(); ok {
		_spec.SetField(link.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := lc.mutation.SavedAt(); ok {
		_spec.SetField(link.FieldSavedAt, field.TypeTime, value)
		_node.SavedAt = value
	}
	if value, ok := lc.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := lc.mutation.PublishedAt(); ok {
		_spec.SetField(link.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	return _node, _spec
}

// LinkCreateBulk is the builder for creating many Link entities in bulk.
type LinkCreateBulk struct {
	config
	err      error
	builders []*LinkCreate
}

// Save creates the Link entities in the database.
func (lcb *LinkCreateBulk) Save(ctx context.Context) ([]*Link, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Link, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LinkCreateBulk) SaveX(ctx context.Context) []*Link {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LinkCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LinkCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
