// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lvncer/quicklinks/api/ent/link"
	"github.com/lvncer/quicklinks/api/ent/predicate"
)

// LinkUpdate is the builder for updating Link entities.
type LinkUpdate struct {
	config
	hooks    []Hook
	mutation *LinkMutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdate) Where(ps ...predicate.Link) *LinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LinkUpdate) SetUserID(v string) *LinkUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableUserID(v *string) *LinkUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LinkUpdate) ClearUserID() *LinkUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetURL sets the "url" field.
func (_u *LinkUpdate) SetURL(v string) *LinkUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableURL(v *string) *LinkUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *LinkUpdate) SetTitle(v string) *LinkUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableTitle(v *string) *LinkUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *LinkUpdate) ClearTitle() *LinkUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *LinkUpdate) SetDescription(v string) *LinkUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableDescription(v *string) *LinkUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LinkUpdate) ClearDescription() *LinkUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *LinkUpdate) SetDomain(v string) *LinkUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableDomain(v *string) *LinkUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *LinkUpdate) ClearDomain() *LinkUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetOgImage sets the "og_image" field.
func (_u *LinkUpdate) SetOgImage(v string) *LinkUpdate {
	_u.mutation.SetOgImage(v)
	return _u
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableOgImage(v *string) *LinkUpdate {
	if v != nil {
		_u.SetOgImage(*v)
	}
	return _u
}

// ClearOgImage clears the value of the "og_image" field.
func (_u *LinkUpdate) ClearOgImage() *LinkUpdate {
	_u.mutation.ClearOgImage()
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *LinkUpdate) SetPageURL(v string) *LinkUpdate {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *LinkUpdate) SetNillablePageURL(v *string) *LinkUpdate {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// ClearPageURL clears the value of the "page_url" field.
func (_u *LinkUpdate) ClearPageURL() *LinkUpdate {
	_u.mutation.ClearPageURL()
	return _u
}

// SetNote sets the "note" field.
func (_u *LinkUpdate) SetNote(v string) *LinkUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableNote(v *string) *LinkUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *LinkUpdate) ClearNote() *LinkUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetTags sets the "tags" field.
func (_u *LinkUpdate) SetTags(v []string) *LinkUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *LinkUpdate) AppendTags(v []string) *LinkUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *LinkUpdate) ClearTags() *LinkUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LinkUpdate) SetMetadata(v map[string]interface{}) *LinkUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetSavedAt sets the "saved_at" field.
func (_u *LinkUpdate) SetSavedAt(v time.Time) *LinkUpdate {
	_u.mutation.SetSavedAt(v)
	return _u
}

// SetNillableSavedAt sets the "saved_at" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableSavedAt(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetSavedAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LinkUpdate) SetCreatedAt(v time.Time) *LinkUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableCreatedAt(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *LinkUpdate) SetPublishedAt(v time.Time) *LinkUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *LinkUpdate) SetNillablePublishedAt(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *LinkUpdate) ClearPublishedAt() *LinkUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdate) Mutation() *LinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdate) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(link.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(link.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(link.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(link.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(link.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.OgImage(); ok {
		_spec.SetField(link.FieldOgImage, field.TypeString, value)
	}
	if _u.mutation.OgImageCleared() {
		_spec.ClearField(link.FieldOgImage, field.TypeString)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(link.FieldPageURL, field.TypeString, value)
	}
	if _u.mutation.PageURLCleared() {
		_spec.ClearField(link.FieldPageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(link.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(link.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(link.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, link.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(link.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(link.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SavedAt(); ok {
		_spec.SetField(link.FieldSavedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(link.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(link.FieldPublishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkUpdateOne is the builder for updating a single Link entity.
type LinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkMutation
}

// SetUserID sets the "user_id" field.
func (_u *LinkUpdateOne) SetUserID(v string) *LinkUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableUserID(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LinkUpdateOne) ClearUserID() *LinkUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetURL sets the "url" field.
func (_u *LinkUpdateOne) SetURL(v string) *LinkUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableURL(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *LinkUpdateOne) SetTitle(v string) *LinkUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableTitle(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *LinkUpdateOne) ClearTitle() *LinkUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetDescription sets the "description" field.
func (_u *LinkUpdateOne) SetDescription(v string) *LinkUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableDescription(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LinkUpdateOne) ClearDescription() *LinkUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *LinkUpdateOne) SetDomain(v string) *LinkUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableDomain(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *LinkUpdateOne) ClearDomain() *LinkUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetOgImage sets the "og_image" field.
func (_u *LinkUpdateOne) SetOgImage(v string) *LinkUpdateOne {
	_u.mutation.SetOgImage(v)
	return _u
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableOgImage(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetOgImage(*v)
	}
	return _u
}

// ClearOgImage clears the value of the "og_image" field.
func (_u *LinkUpdateOne) ClearOgImage() *LinkUpdateOne {
	_u.mutation.ClearOgImage()
	return _u
}

// SetPageURL sets the "page_url" field.
func (_u *LinkUpdateOne) SetPageURL(v string) *LinkUpdateOne {
	_u.mutation.SetPageURL(v)
	return _u
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillablePageURL(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetPageURL(*v)
	}
	return _u
}

// ClearPageURL clears the value of the "page_url" field.
func (_u *LinkUpdateOne) ClearPageURL() *LinkUpdateOne {
	_u.mutation.ClearPageURL()
	return _u
}

// SetNote sets the "note" field.
func (_u *LinkUpdateOne) SetNote(v string) *LinkUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableNote(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *LinkUpdateOne) ClearNote() *LinkUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetTags sets the "tags" field.
func (_u *LinkUpdateOne) SetTags(v []string) *LinkUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *LinkUpdateOne) AppendTags(v []string) *LinkUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *LinkUpdateOne) ClearTags() *LinkUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LinkUpdateOne) SetMetadata(v map[string]interface{}) *LinkUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetSavedAt sets the "saved_at" field.
func (_u *LinkUpdateOne) SetSavedAt(v time.Time) *LinkUpdateOne {
	_u.mutation.SetSavedAt(v)
	return _u
}

// SetNillableSavedAt sets the "saved_at" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableSavedAt(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetSavedAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LinkUpdateOne) SetCreatedAt(v time.Time) *LinkUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableCreatedAt(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *LinkUpdateOne) SetPublishedAt(v time.Time) *LinkUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillablePublishedAt(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *LinkUpdateOne) ClearPublishedAt() *LinkUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdateOne) Mutation() *LinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdateOne) Where(ps ...predicate.Link) *LinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkUpdateOne) Select(field string, fields ...string) *LinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Link entity.
func (_u *LinkUpdateOne) Save(ctx context.Context) (*Link, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdateOne) SaveX(ctx context.Context) *Link {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdateOne) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkUpdateOne) sqlSave(ctx context.Context) (_node *Link, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Link.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, link.FieldID)
		for _, f := range fields {
			if !link.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != link.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(link.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(link.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(link.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(link.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(link.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.OgImage(); ok {
		_spec.SetField(link.FieldOgImage, field.TypeString, value)
	}
	if _u.mutation.OgImageCleared() {
		_spec.ClearField(link.FieldOgImage, field.TypeString)
	}
	if value, ok := _u.mutation.PageURL(); ok {
		_spec.SetField(link.FieldPageURL, field.TypeString, value)
	}
	if _u.mutation.PageURLCleared() {
		_spec.ClearField(link.FieldPageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(link.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(link.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(link.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, link.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(link.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(link.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SavedAt(); ok {
		_spec.SetField(link.FieldSavedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(link.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(link.FieldPublishedAt, field.TypeTime)
	}
	_node = &Link{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
