// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lvncer/quicklinks/api/ent/link"
	"github.com/lvncer/quicklinks/api/ent/predicate"
)

// LinkUpdate is the builder for updating Link entities.
type LinkUpdate struct {
	config
	hooks    []Hook
	mutation *LinkMutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (lu *LinkUpdate) Where(ps ...predicate.Link) *LinkUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetUserID sets the "user_id" field.
func (lu *LinkUpdate) SetUserID(s string) *LinkUpdate {
	lu.mutation.SetUserID(s)
	return lu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableUserID(s *string) *LinkUpdate {
	if s != nil {
		lu.SetUserID(*s)
	}
	return lu
}

// ClearUserID clears the value of the "user_id" field.
func (lu *LinkUpdate) ClearUserID() *LinkUpdate {
	lu.mutation.ClearUserID()
	return lu
}

// SetURL sets the "url" field.
func (lu *LinkUpdate) SetURL(s string) *LinkUpdate {
	lu.mutation.SetURL(s)
	return lu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableURL(s *string) *LinkUpdate {
	if s != nil {
		lu.SetURL(*s)
	}
	return lu
}

// SetTitle sets the "title" field.
func (lu *LinkUpdate) SetTitle(s string) *LinkUpdate {
	lu.mutation.SetTitle(s)
	return lu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableTitle(s *string) *LinkUpdate {
	if s != nil {
		lu.SetTitle(*s)
	}
	return lu
}

// ClearTitle clears the value of the "title" field.
func (lu *LinkUpdate) ClearTitle() *LinkUpdate {
	lu.mutation.ClearTitle()
	return lu
}

// SetDescription sets the "description" field.
func (lu *LinkUpdate) SetDescription(s string) *LinkUpdate {
	lu.mutation.SetDescription(s)
	return lu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableDescription(s *string) *LinkUpdate {
	if s != nil {
		lu.SetDescription(*s)
	}
	return lu
}

// ClearDescription clears the value of the "description" field.
func (lu *LinkUpdate) ClearDescription() *LinkUpdate {
	lu.mutation.ClearDescription()
	return lu
}

// SetDomain sets the "domain" field.
func (lu *LinkUpdate) SetDomain(s string) *LinkUpdate {
	lu.mutation.SetDomain(s)
	return lu
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableDomain(s *string) *LinkUpdate {
	if s != nil {
		lu.SetDomain(*s)
	}
	return lu
}

// ClearDomain clears the value of the "domain" field.
func (lu *LinkUpdate) ClearDomain() *LinkUpdate {
	lu.mutation.ClearDomain()
	return lu
}

// SetOgImage sets the "og_image" field.
func (lu *LinkUpdate) SetOgImage(s string) *LinkUpdate {
	lu.mutation.SetOgImage(s)
	return lu
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableOgImage(s *string) *LinkUpdate {
	if s != nil {
		lu.SetOgImage(*s)
	}
	return lu
}

// ClearOgImage clears the value of the "og_image" field.
func (lu *LinkUpdate) ClearOgImage() *LinkUpdate {
	lu.mutation.ClearOgImage()
	return lu
}

// SetPageURL sets the "page_url" field.
func (lu *LinkUpdate) SetPageURL(s string) *LinkUpdate {
	lu.mutation.SetPageURL(s)
	return lu
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (lu *LinkUpdate) SetNillablePageURL(s *string) *LinkUpdate {
	if s != nil {
		lu.SetPageURL(*s)
	}
	return lu
}

// ClearPageURL clears the value of the "page_url" field.
func (lu *LinkUpdate) ClearPageURL() *LinkUpdate {
	lu.mutation.ClearPageURL()
	return lu
}

// SetNote sets the "note" field.
func (lu *LinkUpdate) SetNote(s string) *LinkUpdate {
	lu.mutation.SetNote(s)
	return lu
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableNote(s *string) *LinkUpdate {
	if s != nil {
		lu.SetNote(*s)
	}
	return lu
}

// ClearNote clears the value of the "note" field.
func (lu *LinkUpdate) ClearNote() *LinkUpdate {
	lu.mutation.ClearNote()
	return lu
}

// SetTags sets the "tags" field.
func (lu *LinkUpdate) SetTags(s []string) *LinkUpdate {
	lu.mutation.SetTags(s)
	return lu
}

// AppendTags appends s to the "tags" field.
func (lu *LinkUpdate) AppendTags(s []string) *LinkUpdate {
	lu.mutation.AppendTags(s)
	return lu
}

// ClearTags clears the value of the "tags" field.
func (lu *LinkUpdate) ClearTags() *LinkUpdate {
	lu.mutation.ClearTags()
	return lu
}

// SetMetadata sets the "metadata" field.
func (lu *LinkUpdate) SetMetadata(m map[string]interface{}) *LinkUpdate {
	lu.mutation.SetMetadata(m)
	return lu
}

// SetSavedAt sets the "saved_at" field.
func (lu *LinkUpdate) SetSavedAt(t time.Time) *LinkUpdate {
	lu.mutation.SetSavedAt(t)
	return lu
}

// SetNillableSavedAt sets the "saved_at" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableSavedAt(t *time.Time) *LinkUpdate {
	if t != nil {
		lu.SetSavedAt(*t)
	}
	return lu
}

// SetCreatedAt sets the "created_at" field.
func (lu *LinkUpdate) SetCreatedAt(t time.Time) *LinkUpdate {
	lu.mutation.SetCreatedAt(t)
	return lu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableCreatedAt(t *time.Time) *LinkUpdate {
	if t != nil {
		lu.SetCreatedAt(*t)
	}
	return lu
}

// SetPublishedAt sets the "published_at" field.
func (lu *LinkUpdate) SetPublishedAt(t time.Time) *LinkUpdate {
	lu.mutation.SetPublishedAt(t)
	return lu
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (lu *LinkUpdate) SetNillablePublishedAt(t *time.Time) *LinkUpdate {
	if t != nil {
		lu.SetPublishedAt(*t)
	}
	return lu
}

// ClearPublishedAt clears the value of the "published_at" field.
func (lu *LinkUpdate) ClearPublishedAt() *LinkUpdate {
	lu.mutation.ClearPublishedAt()
	return lu
}

// Mutation returns the LinkMutation object of the builder.
func (lu *LinkUpdate) Mutation() *LinkMutation {
	return lu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LinkUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LinkUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LinkUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LinkUpdate) check() error {
	if v, ok := lu.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	return nil
}

func (lu *LinkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.UserID(); ok {
		_spec.SetField(link.FieldUserID, field.TypeString, value)
	}
	if lu.mutation.UserIDCleared() {
		_spec.ClearField(link.FieldUserID, field.TypeString)
	}
	if value, ok := lu.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := lu.mutation.Title(); ok {
		_spec.SetField(link.FieldTitle, field.TypeString, value)
	}
	if lu.mutation.TitleCleared() {
		_spec.ClearField(link.FieldTitle, field.TypeString)
	}
	if value, ok := lu.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if lu.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := lu.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
	}
	if lu.mutation.DomainCleared() {
		_spec.ClearField(link.FieldDomain, field.TypeString)
	}
	if value, ok := lu.mutation.OgImage(); ok {
		_spec.SetField(link.FieldOgImage, field.TypeString, value)
	}
	if lu.mutation.OgImageCleared() {
		_spec.ClearField(link.FieldOgImage, field.TypeString)
	}
	if value, ok := lu.mutation.PageURL(); ok {
		_spec.SetField(link.FieldPageURL, field.TypeString, value)
	}
	if lu.mutation.PageURLCleared() {
		_spec.ClearField(link.FieldPageURL, field.TypeString)
	}
	if value, ok := lu.mutation.Note(); ok {
		_spec.SetField(link.FieldNote, field.TypeString, value)
	}
	if lu.mutation.NoteCleared() {
		_spec.ClearField(link.FieldNote, field.TypeString)
	}
	if value, ok := lu.mutation.Tags(); ok {
		_spec.SetField(link.FieldTags, field.TypeJSON, value)
	}
	if value, ok := lu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, link.FieldTags, value)
		})
	}
	if lu.mutation.TagsCleared() {
		_spec.ClearField(link.FieldTags, field.TypeJSON)
	}
	if value, ok := lu.mutation.Metadata(); ok {
		_spec.SetField(link.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := lu.mutation.SavedAt(); ok {
		_spec.SetField(link.FieldSavedAt, field.TypeTime, value)
	}
	if value, ok := lu.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := lu.mutation.PublishedAt(); ok {
		_spec.SetField(link.FieldPublishedAt, field.TypeTime, value)
	}
	if lu.mutation.PublishedAtCleared() {
		_spec.ClearField(link.FieldPublishedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LinkUpdateOne is the builder for updating a single Link entity.
type LinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkMutation
}

// SetUserID sets the "user_id" field.
func (luo *LinkUpdateOne) SetUserID(s string) *LinkUpdateOne {
	luo.mutation.SetUserID(s)
	return luo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableUserID(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetUserID(*s)
	}
	return luo
}

// ClearUserID clears the value of the "user_id" field.
func (luo *LinkUpdateOne) ClearUserID() *LinkUpdateOne {
	luo.mutation.ClearUserID()
	return luo
}

// SetURL sets the "url" field.
func (luo *LinkUpdateOne) SetURL(s string) *LinkUpdateOne {
	luo.mutation.SetURL(s)
	return luo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableURL(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetURL(*s)
	}
	return luo
}

// SetTitle sets the "title" field.
func (luo *LinkUpdateOne) SetTitle(s string) *LinkUpdateOne {
	luo.mutation.SetTitle(s)
	return luo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableTitle(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetTitle(*s)
	}
	return luo
}

// ClearTitle clears the value of the "title" field.
func (luo *LinkUpdateOne) ClearTitle() *LinkUpdateOne {
	luo.mutation.ClearTitle()
	return luo
}

// SetDescription sets the "description" field.
func (luo *LinkUpdateOne) SetDescription(s string) *LinkUpdateOne {
	luo.mutation.SetDescription(s)
	return luo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableDescription(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetDescription(*s)
	}
	return luo
}

// ClearDescription clears the value of the "description" field.
func (luo *LinkUpdateOne) ClearDescription() *LinkUpdateOne {
	luo.mutation.ClearDescription()
	return luo
}

// SetDomain sets the "domain" field.
func (luo *LinkUpdateOne) SetDomain(s string) *LinkUpdateOne {
	luo.mutation.SetDomain(s)
	return luo
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableDomain(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetDomain(*s)
	}
	return luo
}

// ClearDomain clears the value of the "domain" field.
func (luo *LinkUpdateOne) ClearDomain() *LinkUpdateOne {
	luo.mutation.ClearDomain()
	return luo
}

// SetOgImage sets the "og_image" field.
func (luo *LinkUpdateOne) SetOgImage(s string) *LinkUpdateOne {
	luo.mutation.SetOgImage(s)
	return luo
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableOgImage(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetOgImage(*s)
	}
	return luo
}

// ClearOgImage clears the value of the "og_image" field.
func (luo *LinkUpdateOne) ClearOgImage() *LinkUpdateOne {
	luo.mutation.ClearOgImage()
	return luo
}

// SetPageURL sets the "page_url" field.
func (luo *LinkUpdateOne) SetPageURL(s string) *LinkUpdateOne {
	luo.mutation.SetPageURL(s)
	return luo
}

// SetNillablePageURL sets the "page_url" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillablePageURL(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetPageURL(*s)
	}
	return luo
}

// ClearPageURL clears the value of the "page_url" field.
func (luo *LinkUpdateOne) ClearPageURL() *LinkUpdateOne {
	luo.mutation.ClearPageURL()
	return luo
}

// SetNote sets the "note" field.
func (luo *LinkUpdateOne) SetNote(s string) *LinkUpdateOne {
	luo.mutation.SetNote(s)
	return luo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableNote(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetNote(*s)
	}
	return luo
}

// ClearNote clears the value of the "note" field.
func (luo *LinkUpdateOne) ClearNote() *LinkUpdateOne {
	luo.mutation.ClearNote()
	return luo
}

// SetTags sets the "tags" field.
func (luo *LinkUpdateOne) SetTags(s []string) *LinkUpdateOne {
	luo.mutation.SetTags(s)
	return luo
}

// AppendTags appends s to the "tags" field.
func (luo *LinkUpdateOne) AppendTags(s []string) *LinkUpdateOne {
	luo.mutation.AppendTags(s)
	return luo
}

// ClearTags clears the value of the "tags" field.
func (luo *LinkUpdateOne) ClearTags() *LinkUpdateOne {
	luo.mutation.ClearTags()
	return luo
}

// SetMetadata sets the "metadata" field.
func (luo *LinkUpdateOne) SetMetadata(m map[string]interface{}) *LinkUpdateOne {
	luo.mutation.SetMetadata(m)
	return luo
}

// SetSavedAt sets the "saved_at" field.
func (luo *LinkUpdateOne) SetSavedAt(t time.Time) *LinkUpdateOne {
	luo.mutation.SetSavedAt(t)
	return luo
}

// SetNillableSavedAt sets the "saved_at" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableSavedAt(t *time.Time) *LinkUpdateOne {
	if t != nil {
		luo.SetSavedAt(*t)
	}
	return luo
}

// SetCreatedAt sets the "created_at" field.
func (luo *LinkUpdateOne) SetCreatedAt(t time.Time) *LinkUpdateOne {
	luo.mutation.SetCreatedAt(t)
	return luo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableCreatedAt(t *time.Time) *LinkUpdateOne {
	if t != nil {
		luo.SetCreatedAt(*t)
	}
	return luo
}

// SetPublishedAt sets the "published_at" field.
func (luo *LinkUpdateOne) SetPublishedAt(t time.Time) *LinkUpdateOne {
	luo.mutation.SetPublishedAt(t)
	return luo
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillablePublishedAt(t *time.Time) *LinkUpdateOne {
	if t != nil {
		luo.SetPublishedAt(*t)
	}
	return luo
}

// ClearPublishedAt clears the value of the "published_at" field.
func (luo *LinkUpdateOne) ClearPublishedAt() *LinkUpdateOne {
	luo.mutation.ClearPublishedAt()
	return luo
}

// Mutation returns the LinkMutation object of the builder.
func (luo *LinkUpdateOne) Mutation() *LinkMutation {
	return luo.mutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (luo *LinkUpdateOne) Where(ps ...predicate.Link) *LinkUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LinkUpdateOne) Select(field string, fields ...string) *LinkUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Link entity.
func (luo *LinkUpdateOne) Save(ctx context.Context) (*Link, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LinkUpdateOne) SaveX(ctx context.Context) *Link {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LinkUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LinkUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LinkUpdateOne) check() error {
	if v, ok := luo.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	return nil
}

func (luo *LinkUpdateOne) sqlSave(ctx context.Context) (_node *Link, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Link.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, link.FieldID)
		for _, f := range fields {
			if !link.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != link.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.UserID(); ok {
		_spec.SetField(link.FieldUserID, field.TypeString, value)
	}
	if luo.mutation.UserIDCleared() {
		_spec.ClearField(link.FieldUserID, field.TypeString)
	}
	if value, ok := luo.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := luo.mutation.Title(); ok {
		_spec.SetField(link.FieldTitle, field.TypeString, value)
	}
	if luo.mutation.TitleCleared() {
		_spec.ClearField(link.FieldTitle, field.TypeString)
	}
	if value, ok := luo.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if luo.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := luo.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
	}
	if luo.mutation.DomainCleared() {
		_spec.ClearField(link.FieldDomain, field.TypeString)
	}
	if value, ok := luo.mutation.OgImage(); ok {
		_spec.SetField(link.FieldOgImage, field.TypeString, value)
	}
	if luo.mutation.OgImageCleared() {
		_spec.ClearField(link.FieldOgImage, field.TypeString)
	}
	if value, ok := luo.mutation.PageURL(); ok {
		_spec.SetField(link.FieldPageURL, field.TypeString, value)
	}
	if luo.mutation.PageURLCleared() {
		_spec.ClearField(link.FieldPageURL, field.TypeString)
	}
	if value, ok := luo.mutation.Note(); ok {
		_spec.SetField(link.FieldNote, field.TypeString, value)
	}
	if luo.mutation.NoteCleared() {
		_spec.ClearField(link.FieldNote, field.TypeString)
	}
	if value, ok := luo.mutation.Tags(); ok {
		_spec.SetField(link.FieldTags, field.TypeJSON, value)
	}
	if value, ok := luo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, link.FieldTags, value)
		})
	}
	if luo.mutation.TagsCleared() {
		_spec.ClearField(link.FieldTags, field.TypeJSON)
	}
	if value, ok := luo.mutation.Metadata(); ok {
		_spec.SetField(link.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := luo.mutation.SavedAt(); ok {
		_spec.SetField(link.FieldSavedAt, field.TypeTime, value)
	}
	if value, ok := luo.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := luo.mutation.PublishedAt(); ok {
		_spec.SetField(link.FieldPublishedAt, field.TypeTime, value)
	}
	if luo.mutation.PublishedAtCleared() {
		_spec.ClearField(link.FieldPublishedAt, field.TypeTime)
	}
	_node = &Link{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
