// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/lvncer/quicklinks/api/ent/link"
	"github.com/lvncer/quicklinks/api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	linkFields := schema.Link{}.Fields()
	_ = linkFields
	// linkDescURL is the schema descriptor for url field.
	linkDescURL := linkFields[2].Descriptor()
	// link.URLValidator is a validator for the "url" field. It is called by the builders before save.
	link.URLValidator = linkDescURL.Validators[0].(func(string) error)
	// linkDescMetadata is the schema descriptor for metadata field.
	linkDescMetadata := linkFields[10].Descriptor()
	// link.DefaultMetadata holds the default value on creation for the metadata field.
	link.DefaultMetadata = linkDescMetadata.Default.(map[string]interface{})
	// linkDescSavedAt is the schema descriptor for saved_at field.
	linkDescSavedAt := linkFields[11].Descriptor()
	// link.DefaultSavedAt holds the default value on creation for the saved_at field.
	link.DefaultSavedAt = linkDescSavedAt.Default.(func() time.Time)
	// linkDescCreatedAt is the schema descriptor for created_at field.
	linkDescCreatedAt := linkFields[12].Descriptor()
	// link.DefaultCreatedAt holds the default value on creation for the created_at field.
	link.DefaultCreatedAt = linkDescCreatedAt.Default.(func() time.Time)
	// linkDescID is the schema descriptor for id field.
	linkDescID := linkFields[0].Descriptor()
	// link.DefaultID holds the default value on creation for the id field.
	link.DefaultID = linkDescID.Default.(func() uuid.UUID)
}
